{
    "custom-styles": {
        "Alerts": {
            "Region Marker": {
                "background-color": "#aa00ff",
                "selected-text-color": "#ff0000",
                "text-color": "#ff0000"
            }
        },
        "Comments": {
            "Comment": {
                "selected-text-color": "#353931",
                "text-color": "#31312c"
            }
        },
        "Doxygen": {
            "Entities": {
                "selected-text-color": "#aa557f",
                "text-color": "#aa00ff"
            },
            "HTML Comment": {
                "selected-text-color": "#1e1d1b",
                "text-color": "#23231f"
            }
        },
        "JavaScript": {
            "Binary": {
                "selected-text-color": "#ffffff",
                "text-color": "#ffffff"
            },
            "Built-in Objects": {
                "selected-text-color": "#ffff00",
                "text-color": "#ffff00"
            },
            "Decimal": {
                "selected-text-color": "#ffffff",
                "text-color": "#ffffff"
            },
            "Float": {
                "selected-text-color": "#ffffff",
                "text-color": "#ffffff"
            },
            "Function (Built-in)": {
                "selected-text-color": "#ff5500",
                "text-color": "#ffaa00"
            },
            "Hex": {
                "selected-text-color": "#ffffff",
                "text-color": "#ffffff"
            },
            "Octal": {
                "selected-text-color": "#ffffff",
                "text-color": "#ffffff"
            },
            "String": {
                "selected-text-color": "#c7ff4f",
                "text-color": "#ffd940"
            },
            "Substitution": {
                "selected-text-color": "#550000",
                "text-color": "#550000"
            }
        },
        "Modelines": {
            "Option OFF": {
                "selected-text-color": "#550000",
                "text-color": "#aa0000"
            },
            "Option ON": {
                "selected-text-color": "#005500",
                "text-color": "#005500"
            },
            "Value": {
                "selected-text-color": "#a2a200",
                "text-color": "#ffff00"
            }
        }
    },
    "editor-colors": {
        "BackgroundColor": "#000000",
        "BracketMatching": "#4400aa",
        "CodeFolding": "#002b26",
        "CurrentLine": "#17003b",
        "CurrentLineNumber": "#ffaa00",
        "IconBorder": "#000000",
        "IndentationLine": "#d2c508",
        "LineNumbers": "#ffff00",
        "MarkBookmark": "#ff5500",
        "MarkBreakpointActive": "#ff0000",
        "MarkBreakpointDisabled": "#ff00ff",
        "MarkBreakpointReached": "#ffff00",
        "MarkError": "#ff0000",
        "MarkExecution": "#a0a0a4",
        "MarkWarning": "#ffff00",
        "ModifiedLines": "#54ff54",
        "ReplaceHighlight": "#54ff54",
        "SavedLines": "#00aa00",
        "SearchHighlight": "#ffff00",
        "Separator": "#003344",
        "SpellChecking": "#ff0000",
        "TabMarker": "#414141",
        "TemplateBackground": "#cccccc",
        "TemplateFocusedPlaceholder": "#66ff66",
        "TemplatePlaceholder": "#ccffcc",
        "TemplateReadOnlyPlaceholder": "#ffcccc",
        "TextSelection": "#232323",
        "WordWrapMarker": "#262626"
    },
    "metadata": {
        "name": "Vim Dark Custom",
        "revision": 1
    },
    "text-styles": {
        "Alert": {
            "background-color": "#3f0000",
            "bold": true,
            "selected-text-color": "#bf0303",
            "text-color": "#ff0000"
        },
        "Annotation": {
            "selected-text-color": "#ffaa00",
            "text-color": "#ffff00"
        },
        "Attribute": {
            "selected-text-color": "#ffffaf",
            "text-color": "#ffffaf"
        },
        "BaseN": {
            "selected-text-color": "#ffffff",
            "text-color": "#ffffff"
        },
        "BuiltIn": {
            "bold": true,
            "selected-text-color": "#55007f",
            "text-color": "#55007f"
        },
        "Char": {
            "selected-text-color": "#ff0b44",
            "text-color": "#ff2142"
        },
        "Comment": {
            "selected-text-color": "#071414",
            "text-color": "#2f2e2b"
        },
        "CommentVar": {
            "selected-text-color": "#ffaa00",
            "text-color": "#ffff00"
        },
        "Constant": {
            "bold": true,
            "selected-text-color": "#af7f00",
            "text-color": "#af7f00"
        },
        "ControlFlow": {
            "bold": true,
            "selected-text-color": "#ffff54",
            "text-color": "#ffff54"
        },
        "DataType": {
            "selected-text-color": "#ffff54",
            "text-color": "#ffff54"
        },
        "DecVal": {
            "selected-text-color": "#ffffff",
            "text-color": "#ffffff"
        },
        "Documentation": {
            "selected-text-color": "#e0ffff",
            "text-color": "#e0ffff"
        },
        "Error": {
            "selected-text-color": "#ff5500",
            "text-color": "#ff5500",
            "underline": true
        },
        "Extension": {
            "bold": true,
            "selected-text-color": "#ffff00",
            "text-color": "#ff5500"
        },
        "Float": {
            "selected-text-color": "#ffffff",
            "text-color": "#ffffff"
        },
        "Function": {
            "selected-text-color": "#ffaa00",
            "text-color": "#ffff00"
        },
        "Import": {
            "selected-text-color": "#aa00ff",
            "text-color": "#aa007f"
        },
        "Information": {
            "selected-text-color": "#ffaa00",
            "text-color": "#ffaa00"
        },
        "Keyword": {
            "bold": true,
            "selected-text-color": "#e0ffff",
            "text-color": "#5fd7ff"
        },
        "Normal": {
            "selected-text-color": "#b2b2b2",
            "text-color": "#b2b2b2"
        },
        "Operator": {
            "selected-text-color": "#b2b2b2",
            "text-color": "#b2b2b2"
        },
        "Others": {
            "selected-text-color": "#54ff54",
            "text-color": "#54ff54"
        },
        "Preprocessor": {
            "selected-text-color": "#ff5500",
            "text-color": "#ff5500"
        },
        "RegionMarker": {
            "background-color": "#000000",
            "selected-text-color": "#ffaa00",
            "text-color": "#ffff00"
        },
        "SpecialChar": {
            "selected-text-color": "#aa0000",
            "text-color": "#ff0000"
        },
        "SpecialString": {
            "selected-text-color": "#ff5500",
            "text-color": "#ff5500"
        },
        "String": {
            "selected-text-color": "#ff54ff",
            "text-color": "#ff54ff"
        },
        "Variable": {
            "selected-text-color": "#06989a",
            "text-color": "#06989a"
        },
        "VerbatimString": {
            "selected-text-color": "#f000f0",
            "text-color": "#f000f0"
        },
        "Warning": {
            "selected-text-color": "#ed1515",
            "text-color": "#ff0000"
        }
    }
}
